on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build -c Release Stratum

      - name: Test
        run: dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Push Code Coverage
        uses: codecov/codecov-action@v2.0.2
        with:
          files: Stratum.Tests/coverage.opencover.xml

      - name: Pack Thunderstore
        run: thunderstore/pack.sh

      - name: Upload Thunderstore
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: thunderstore/out/*

      - name: Pack NuGet
        run: dotnet pack -c Release Stratum

      - name: Upload NuGet
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: Stratum/nupkg/*
