on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'Stratum.sln.DotSettings'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'Stratum.sln.DotSettings'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Pack NuGet
        run: dotnet pack -c Release --no-build Stratum

      - name: Upload Thunderstore
        uses: actions/upload-artifact@v2
        with:
          name: Thunderstore
          path: Stratum/thunderstore/out/*

      - name: Upload NuGet
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: Stratum/nupkg/*

      - name: Push Code Coverage
        uses: codecov/codecov-action@v2.0.2
        with:
          files: Stratum.Tests/coverage.opencover.xml
