name: Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  src:
    name: Package Stratum
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build -c Release Stratum

      - name: Pack
        run: dotnet pack -c Release --no-build Stratum

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Stratum
          path: |
            Stratum/nupkg/*.nupkg
            Stratum/nupkg/*.snupkg
